### ISSUE TITLE
[Machine] Discharge modes not available

### ISSUE THREAD

**Issue by Wreyth** [scfmod/FS22_TerraFarm#102]
am i missing something or is there no setting for discharging raise/ smooth ect ect 

i did see the allow raising but still just dumps material on the ground and only way i can raise the ground is digging it up.

**Comment by scfmod** [comment]
Raise ground is not yet implemented. It may be added retroactively, but I have not decided yet due to time constraints. So we'll see if I get time before FS25 is released.

You can enable "Allow grading up" in advanced settings which will allow you to raise terrain using grading mode (disable material input is recommended).

**Comment by scfmod** [comment]
Managed to get some spare time today and implemented discharge modes, not 100% perfect as I'm kind of limited with how the engine works, but should be available for download sometime tommorrow :)

**Comment by Wreyth** [comment]
woot hooray! thanks for all your work!

**Comment by scfmod** [comment]
0.9.6.0 is now available with discharge functionality for shovels and excavator shovels :-)
