### ISSUE TITLE
Feature Request: Ability to set a minimum dig depth

### ISSUE THREAD

**Issue by blackwellj** [scfmod/FS22_TerraFarm#19]
It would be nice to be able to turn on a guide that would limit how deep you can dig. This would be helpful for flattening an area

**Comment by scfmod** [comment]
Yeah would definitely be a good feature to add, I'll have to think of a way to make it easy to use.
I'll look into it when starting on bulldozer support in 0.4 :-)

**Comment by alphaomegarandomname** [comment]
I think it should not be a capped limit but perhaps a readout. Not sure if it can be done outside the clunky F1 interface tho. And it would be up to the operator to follow that limit. This is prevent people just mashing controls without a care ;p

**Comment by blackwellj** [comment]
> I think it should not be a capped limit but perhaps a readout. Not sure if it can be done outside the clunky F1 interface tho. And it would be up to the operator to follow that limit. This is prevent people just mashing controls without a care ;p

The problem with that method is the removal of dirt does not happen on a flat plane like in real life. Eg. If you run a loaded with the bucket flat on the floor it will still dig down. There is no easy way of flattening an area without going over the same ground with multiple different tools. Saying that the Hamm roller works very well to flatten an area

**Comment by alphaomegarandomname** [comment]
I can flatten using excavator bucket just fine. I spent 8 hours building a ramp across a pond the other day.  But yes it is a little weird when it actually digs; not as precise as we would like it to be. Seems to be a sensitivity issue with how instantly and strongly terrain responds. Not sure anything can be done unless giants works on the logic

**Comment by scfmod** [comment]
Yeah there are definitely limitations with how GIANTS have implemented their terrain, and especially with the deform functions exposed from game engine to Lua. There are some possibilities for enhancing the terrain modification I'd like to research more in the future, but the most frustrating part is that the result of deform functions varies between maps with no apparent way to keep it uniform.

Now that with 0.4.0.0 release coming up I have moved most settings to each individual machine (instead of global), so I will look into adding a option there to toggle manually set terrain height for flatten. A similar option for other operations like raise and lower can be possible to implement, but needs more research and probably won't make it into 0.4.0.0.

(There will also be a strength modifier in GUI which will allow you to adjust it between 10-100% in 10% steps.)
