### ISSUE TITLE
Not a issue: Possible support for FS19?

### ISSUE THREAD

**Issue by Rockythelover22** [scfmod/FS22_TerraFarm#22]
I'm thinking since fs22 is still in it's binging life and there is a ton of mods on fs19 making this mod work for construction and others things this is perfect.

**Comment by scfmod** [comment]
It's definitely possible to backport this mod to FS19, but due to having limited time working on this mod (work and real life) I can't support them both :-)
Anyone who is interested in backporting it to FS19 is free to do so, and the amount of work needed to make it work should be minimal (at least for current and older versions of the mod)
