### ISSUE TITLE
unrealistic Maximum Discharge Height for raise /flatten landscape

### ISSUE THREAD

**Issue by alexanderweide** [scfmod/FS22_TerraFarm#28]
Hi,

i really love this mod. I constantly use it.. but when i use the excavator EC750 as well as the Class wheel loader i cannot raise any ground when the shovel is higher than like 30 centimeters above ground. It dosent make any sense that discharging the stones from the shovels cannot occure in bigger distances to the ground.

I was also able to see that lowering/flatten of the ground with greater distance to the ground was easily possible.. 

-> Maybe this is because of the speed how the land will be changed in flatten mode -> its somehow working faster on greater distance to the position of the excavator/loader.

**Comment by scfmod** [comment]
Same as #29, should be working much better with 0.4.0.0 when released.
The main thing causing these issues are due to the limitation of the game engine and the functions exposed to the Lua environment. So there probably won't be a 100% fix for such things. Thanks for reporting!
I'll close this one for now, feel free to open new issue and reference this if you have same problems when 0.4.0.0 is released.
